services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save ""
      --maxmemory 0
      --databases 16
      --aclfile /usr/local/etc/redis/users.acl
    volumes:
      - ./infra/redis/data:/data
      - ./infra/redis/users.acl:/usr/local/etc/redis/users.acl:ro
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10
